# Generated by Django 5.1.7 on 2025-04-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='user_default', max_length=100),
            preserve_default=False,
        ),
    ]
