# Generated by Django 5.1.7 on 2025-04-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0003_challenge_goal_completed_date_goal_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default='anonymous', max_length=100, unique=True),
        ),
    ]
