# Generated by Django 5.1.7 on 2025-04-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0005_alter_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
