# Generated by Django 5.1.7 on 2025-04-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0006_alter_login_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='username',
        ),
    ]
