# Generated by Django 5.1.7 on 2025-04-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0007_remove_login_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='difficulty',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
