# Generated by Django 5.1.7 on 2025-04-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0009_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
