# Generated by Django 5.1.7 on 2025-04-18 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0010_reward_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalapp.login'),
        ),
    ]
