# Generated by Django 5.1.7 on 2025-04-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0011_alter_reward_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='streak_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
