# Generated by Django 5.1.7 on 2025-04-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0012_reward_streak_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='streak_start_date',
        ),
    ]
