# Generated by Django 5.1.7 on 2025-04-18 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0013_remove_reward_streak_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goalapp.goal'),
        ),
    ]
