# Generated by Django 5.1.7 on 2025-04-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0015_diaryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
