# Generated by Django 5.1.7 on 2025-04-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0016_diaryentry_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
