# Generated by Django 5.1.7 on 2025-04-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0017_goal_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default='default_username', max_length=150, unique=True),
        ),
    ]
