# Generated by Django 5.1.7 on 2025-04-22 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0018_login_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='username',
        ),
    ]
