# Generated by Django 5.1.7 on 2025-04-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0021_remove_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
