# Generated by Django 5.1.7 on 2025-04-24 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0022_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
