# Generated by Django 5.1.7 on 2025-05-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0023_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='time',
            field=models.TimeField(),
        ),
    ]
