# Generated by Django 5.1.7 on 2025-05-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0024_alter_diaryentry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
