# Generated by Django 5.1.7 on 2025-05-09 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0025_alter_diaryentry_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='diary_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='goalapp.diaryentry')),
            ],
        ),
    ]
