# Generated by Django 5.1.7 on 2025-05-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0026_diaryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='days_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
