# Generated by Django 5.1.7 on 2025-05-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0027_goal_days_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='days_spent',
        ),
    ]
