# Generated by Django 5.1.7 on 2025-05-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0028_remove_goal_days_spent'),
        ('goalapp', '0028_remove_todo_number_of_goals_completed'),
    ]

    operations = [
    ]
