# Generated by Django 5.1.7 on 2025-05-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0029_merge_20250518_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeparticipation',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='challengeparticipation',
            name='user',
        ),
        migrations.AddField(
            model_name='goal',
            name='days_spent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='ChallengeParticipation',
        ),
    ]
