# Generated by Django 5.1.7 on 2025-05-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0030_remove_challengeparticipation_challenge_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
