# Generated by Django 5.1.7 on 2025-05-20 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0032_challenge_delete_pushsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='session_key',
        ),
        migrations.AddField(
            model_name='challenge',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='goalapp.login'),
            preserve_default=False,
        ),
    ]
