# Generated by Django 5.1.7 on 2025-05-21 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0033_remove_challenge_session_key_challenge_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='goalapp.login'),
        ),
        migrations.CreateModel(
            name='ChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.TextField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='goalapp.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalapp.login')),
            ],
            options={
                'unique_together': {('challenge', 'user')},
            },
        ),
    ]
