# Generated by Django 5.1.7 on 2025-05-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0035_login_groups_login_is_active_login_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='login',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='login',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='login',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='login',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='login',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='user_type',
            field=models.CharField(max_length=100),
        ),
    ]
