# Generated by Django 5.1.7 on 2025-05-22 16:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0036_remove_login_groups_remove_login_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeprogress',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ChallengeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='challenge_updates/%Y/%m/%d/')),
                ('video', models.FileField(blank=True, null=True, upload_to='challenge_updates/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateField(default=django.utils.timezone.now)),
                ('challenge_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='goalapp.challengeprogress')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='goalapp.challengeupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='goalapp.challengeupdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goalapp.login')),
            ],
            options={
                'unique_together': {('update', 'user')},
            },
        ),
    ]
