# Generated by Django 5.1.7 on 2025-05-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0037_challengeprogress_streak_challengeupdate_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
