# Generated by Django 5.1.7 on 2025-05-28 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0040_comment_level_comment_lft_comment_rght_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailycheck',
            old_name='bonus',
            new_name='longest_streak',
        ),
        migrations.RemoveField(
            model_name='dailycheck',
            name='badge',
        ),
        migrations.AddField(
            model_name='dailycheck',
            name='last_streak_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dailycheck',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
