# Generated by Django 5.1.7 on 2025-05-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0041_rename_bonus_dailycheck_longest_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
