# Generated by Django 5.1.7 on 2025-05-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0042_milestone_completed_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['id']},
        ),
    ]
