# Generated by Django 5.1.7 on 2025-05-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0043_alter_milestone_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='milestone',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
