# Generated by Django 5.1.7 on 2025-05-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0049_alter_milestone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
