# Generated by Django 5.1.7 on 2025-06-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0051_aiinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeupdate',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone',
            name='missed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AIInsight',
        ),
    ]
