# Generated by Django 5.1.7 on 2025-06-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0053_remove_challengeupdate_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeupdate',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone',
            name='missed',
            field=models.BooleanField(default=False),
        ),
    ]
