# Generated by Django 5.1.7 on 2025-06-15 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0054_challengeupdate_reported_milestone_missed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='goalapp.login'),
            preserve_default=False,
        ),
    ]
