# Generated by Django 5.1.7 on 2025-06-15 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0057_alter_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
