# Generated by Django 5.1.7 on 2025-06-18 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0060_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(max_length=50)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_notifications', to='goalapp.login')),
            ],
            options={
                'unique_together': {('user', 'notification_id')},
            },
        ),
    ]
