# Generated by Django 5.1.7 on 2025-07-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0061_dismissednotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('mbti_type', models.CharField(max_length=4)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
