# Generated by Django 5.1.7 on 2025-07-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0062_mbtiprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTIExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=4, unique=True)),
                ('description', models.TextField()),
                ('explanation', models.TextField()),
                ('growth_tips', models.JSONField(default=list)),
                ('matches', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.DeleteModel(
            name='MBTIProfile',
        ),
    ]
