# Generated by Django 5.1.7 on 2025-07-10 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalapp', '0063_mbtiexplanation_delete_mbtiprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBTIProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('mbti_type', models.CharField(max_length=4)),
                ('date_taken', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
